pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS=credentials('dockerhub-credentials')
    }

    stages {

        stage ("Run Tests") {
            steps {
                sh 'pip3 install -r requirements.txt'
                sh 'pytest --cov-report xml:coverage.xml --cov . --junitxml=result.xml'
            }
        }

        stage ("Sonarqube")
        {
            steps{
                sh 'docker run --rm --net=host -v ${PWD}:/back-end sonarsource/sonar-scanner-cli sonar-scanner -D sonar.projectBaseDir=/back-end'
            }
        }

        stage ("Build Docker Image") {
            steps {
                sh 'docker build -t eldarmustafayev/abbtech-backend .'
            }
        }

        stage ("Login and push to Dockerhub") {
            steps {
                sh "echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin"
                sh 'docker push eldarmustafayev/abbtech-backend'
            }
        }
        

        stage ("Deploy") {
            steps {
                sh "kubectl apply -f ../kubernetes/secrets.yaml"
                sh "kubectl apply -f ../kubernetes/config.yaml"
                sh "kubectl apply -f ../kubernetes/database.yaml"
                sh "kubectl apply -f ../kubernetes/back-end.yaml"
            }
        }
    }

}